/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.Model;


public class Gui extends javax.swing.JFrame {
        private Model m;
    
    public Gui() {
        initComponents();
        FileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
      //  m.EnableCRUD(false);
      boolean stat=false;
                                getIsEditCHB2().setEnabled(stat);
                                getIsExeCHB2().setEnabled(stat);
                                getIsReadCHB2().setEnabled(stat);
                                getIsDirectoryCHB2().setEnabled(stat);
                                getIsFileCHB2().setEnabled(stat);
                                getIsHiddenCHB2().setEnabled(stat);
                                getCrearBTN().setEnabled(stat);
                                getItemJTF().setEnabled(stat);
                                getEsborrarBTN().setEnabled(stat);
                                getPassejarBTN().setEnabled(stat);
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        isHiddenCHB1 = new javax.swing.JCheckBox();
        IsReadCHB1 = new javax.swing.JCheckBox();
        IsExeCHB1 = new javax.swing.JCheckBox();
        IsEditCHB1 = new javax.swing.JCheckBox();
        isFileCHB1 = new javax.swing.JCheckBox();
        isDirectoryCHB1 = new javax.swing.JCheckBox();
        FileDirectory = new javax.swing.ButtonGroup();
        FileJTF = new javax.swing.JTextField();
        SelectFileBTN = new javax.swing.JButton();
        InfoBTN = new javax.swing.JButton();
        IsReadCHB = new javax.swing.JCheckBox();
        IsExeCHB = new javax.swing.JCheckBox();
        IsEditCHB = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        isFileCHB = new javax.swing.JCheckBox();
        isDirectoryCHB = new javax.swing.JCheckBox();
        isHiddenCHB = new javax.swing.JCheckBox();
        ItemJTF = new javax.swing.JTextField();
        CrearBTN = new javax.swing.JButton();
        EsborrarBTN = new javax.swing.JButton();
        isHiddenCHB2 = new javax.swing.JCheckBox();
        IsReadCHB2 = new javax.swing.JCheckBox();
        IsExeCHB2 = new javax.swing.JCheckBox();
        IsEditCHB2 = new javax.swing.JCheckBox();
        isFileCHB2 = new javax.swing.JRadioButton();
        isDirectoryCHB2 = new javax.swing.JRadioButton();
        PassejarBTN = new javax.swing.JButton();

        isHiddenCHB1.setText("Ocult");

        IsReadCHB1.setText("Llegible");

        IsExeCHB1.setText("Executable");

        IsEditCHB1.setText("Editable");

        isFileCHB1.setText("Fitxer");

        isDirectoryCHB1.setText("Directori");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectFileBTN.setText("Selecciona");

        InfoBTN.setText("Mostrar informació del fitxer seleccionat anteriorment");

        IsReadCHB.setText("Llegible");

        IsExeCHB.setText("Executable");

        IsEditCHB.setText("Editable");

        isFileCHB.setText("Fitxer");

        isDirectoryCHB.setText("Directori");

        isHiddenCHB.setText("Ocult");

        ItemJTF.setText("jTextField1");

        CrearBTN.setText("Crear");
        CrearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBTNActionPerformed(evt);
            }
        });

        EsborrarBTN.setText("Borrar");

        isHiddenCHB2.setText("Read Only");

        IsReadCHB2.setText("Llegible");

        IsExeCHB2.setText("Executable");

        IsEditCHB2.setText("Editable");

        FileDirectory.add(isFileCHB2);
        isFileCHB2.setText("Fitxer");

        FileDirectory.add(isDirectoryCHB2);
        isDirectoryCHB2.setText("Directori");

        PassejarBTN.setText("Passejar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FileJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectFileBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addComponent(InfoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isFileCHB)
                            .addComponent(isHiddenCHB)
                            .addComponent(isDirectoryCHB))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(isDirectoryCHB2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(isHiddenCHB2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IsEditCHB2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(isFileCHB2)
                                    .addGap(27, 27, 27)
                                    .addComponent(IsExeCHB2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(IsReadCHB2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EsborrarBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(CrearBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IsReadCHB)
                                .addComponent(IsExeCHB)
                                .addComponent(IsEditCHB))
                            .addComponent(PassejarBTN, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FileJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectFileBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isFileCHB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isDirectoryCHB, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isHiddenCHB)
                    .addComponent(InfoBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IsExeCHB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IsReadCHB, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IsEditCHB)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isHiddenCHB2)
                            .addComponent(IsEditCHB2)
                            .addComponent(isDirectoryCHB2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsExeCHB2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsReadCHB2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isFileCHB2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EsborrarBTN)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(PassejarBTN)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearBTNActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
                
            }
        });
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBTN;
    private javax.swing.JButton EsborrarBTN;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.ButtonGroup FileDirectory;
    private javax.swing.JTextField FileJTF;
    private javax.swing.JButton InfoBTN;
    private javax.swing.JCheckBox IsEditCHB;
    private javax.swing.JCheckBox IsEditCHB1;
    private javax.swing.JCheckBox IsEditCHB2;
    private javax.swing.JCheckBox IsExeCHB;
    private javax.swing.JCheckBox IsExeCHB1;
    private javax.swing.JCheckBox IsExeCHB2;
    private javax.swing.JCheckBox IsReadCHB;
    private javax.swing.JCheckBox IsReadCHB1;
    private javax.swing.JCheckBox IsReadCHB2;
    private javax.swing.JTextField ItemJTF;
    private javax.swing.JButton PassejarBTN;
    private javax.swing.JButton SelectFileBTN;
    private javax.swing.JCheckBox isDirectoryCHB;
    private javax.swing.JCheckBox isDirectoryCHB1;
    private javax.swing.JRadioButton isDirectoryCHB2;
    private javax.swing.JCheckBox isFileCHB;
    private javax.swing.JCheckBox isFileCHB1;
    private javax.swing.JRadioButton isFileCHB2;
    private javax.swing.JCheckBox isHiddenCHB;
    private javax.swing.JCheckBox isHiddenCHB1;
    private javax.swing.JCheckBox isHiddenCHB2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getIsEditCHB() {
        return IsEditCHB;
    }

    public void setIsEditCHB(JCheckBox IsEditCHB) {
        this.IsEditCHB = IsEditCHB;
    }

    public JCheckBox getIsExeCHB() {
        return IsExeCHB;
    }

    public void setIsExeCHB(JCheckBox IsExeCHB) {
        this.IsExeCHB = IsExeCHB;
    }

    public JCheckBox getIsReadCHB() {
        return IsReadCHB;
    }

    public void setIsReadCHB(JCheckBox IsReadCHB) {
        this.IsReadCHB = IsReadCHB;
    }

    public JCheckBox getIsDirectoryCHB() {
        return isDirectoryCHB;
    }

    public void setIsDirectoryCHB(JCheckBox isDirectoryCHB) {
        this.isDirectoryCHB = isDirectoryCHB;
    }

    public JCheckBox getIsFileCHB() {
        return isFileCHB;
    }

    public void setIsFileCHB(JCheckBox isFileCHB) {
        this.isFileCHB = isFileCHB;
    }

    public JCheckBox getIsHiddenCHB() {
        return isHiddenCHB;
    }

    public void setIsHiddenCHB(JCheckBox isHiddenCHB) {
        this.isHiddenCHB = isHiddenCHB;
    }

    public JButton getInfoBTN() {
        return InfoBTN;
    }

    public void setInfoBTN(JButton InfoBTN) {
        this.InfoBTN = InfoBTN;
    }

    public JButton getSelectFileBTN() {
        return SelectFileBTN;
    }

    public void setSelectFileBTN(JButton SelectFileBTN) {
        this.SelectFileBTN = SelectFileBTN;
    }

    public JFileChooser getFileChooser() {
        return FileChooser;
    }

    public void setFileChooser(JFileChooser FileChooser) {
        this.FileChooser = FileChooser;
    }

    public JTextField getFileJTF() {
        return FileJTF;
    }

    public void setFileJTF(JTextField FileJTF) {
        this.FileJTF = FileJTF;
    }

    public JButton getCrearBTN() {
        return CrearBTN;
    }

    public void setCrearBTN(JButton CrearBTN) {
        this.CrearBTN = CrearBTN;
    }

    public JTextField getItemJTF() {
        return ItemJTF;
    }

    public void setItemJTF(JTextField ItemJTF) {
        this.ItemJTF = ItemJTF;
    }

    public JCheckBox getIsEditCHB2() {
        return IsEditCHB2;
    }

    public void setIsEditCHB2(JCheckBox IsEditCHB2) {
        this.IsEditCHB2 = IsEditCHB2;
    }

    public JCheckBox getIsExeCHB2() {
        return IsExeCHB2;
    }

    public void setIsExeCHB2(JCheckBox IsExeCHB2) {
        this.IsExeCHB2 = IsExeCHB2;
    }

    public JCheckBox getIsReadCHB2() {
        return IsReadCHB2;
    }

    public void setIsReadCHB2(JCheckBox IsReadCHB2) {
        this.IsReadCHB2 = IsReadCHB2;
    }

    public JRadioButton getIsDirectoryCHB2() {
        return isDirectoryCHB2;
    }

    public void setIsDirectoryCHB2(JRadioButton isDirectoryCHB2) {
        this.isDirectoryCHB2 = isDirectoryCHB2;
    }

    public JRadioButton getIsFileCHB2() {
        return isFileCHB2;
    }

    public void setIsFileCHB2(JRadioButton isFileCHB2) {
        this.isFileCHB2 = isFileCHB2;
    }

    public JCheckBox getIsHiddenCHB2() {
        return isHiddenCHB2;
    }

    public void setIsHiddenCHB2(JCheckBox isHiddenCHB2) {
        this.isHiddenCHB2 = isHiddenCHB2;
    }

    public JButton getEsborrarBTN() {
        return EsborrarBTN;
    }

    public void setEsborrarBTN(JButton EsborrarBTN) {
        this.EsborrarBTN = EsborrarBTN;
    }

    public JButton getPassejarBTN() {
        return PassejarBTN;
    }

    public void setPassejarBTN(JButton PassejarBTN) {
        this.PassejarBTN = PassejarBTN;
    }

    
    
    
    

   

    
    

    

    
}
